[project]
name = "exam-system-architect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pdfplumber>=0.11.9",
    "pymupdf>=1.26.7",
    "pypdf>=6.6.0",
]
